# Generated by Django 5.0.8 on 2024-12-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Administradores', 'Administradores'), ('Lectores', 'Lectores')], default='User', max_length=50),
        ),
    ]
