# Generated by Django 5.0.8 on 2024-12-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_libro_descripcion_libro_portada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
