# Generated by Django 5.0.8 on 2024-12-03 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_libro_estado_membresia_libro_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='estado_membresia',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='numero_membresia',
        ),
        migrations.AddField(
            model_name='profile',
            name='estado_membresia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero_membresia',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
