# Generated by Django 5.0.8 on 2024-12-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_libro_estado_membresia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario'), ('Empleado', 'Empleado')], default='Lector', max_length=50),
        ),
    ]
