# Generated by Django 5.0.8 on 2024-12-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_estado_membresia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numero_membresia',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
