# Generated by Django 5.0.8 on 2024-12-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_profile_numero_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numero_membresia',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
