# Generated by Django 5.0.8 on 2024-12-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_numero_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numero_membresia',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
