# Generated by Django 5.0.8 on 2024-12-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_profile_numero_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='dias_prestamo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(),
        ),
    ]
