# Generated by Django 5.0.8 on 2024-12-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_profile_numero_membresia'),
    ]

    operations = [
    ]
