# Generated by Django 5.0.8 on 2024-12-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20241203_0532'),
    ]

    operations = [
    ]
