# Generated by Django 5.0.8 on 2024-12-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='libros',
            field=models.ManyToManyField(related_name='generos', to='users.libro'),
        ),
    ]
