# Generated by Django 5.0.8 on 2024-12-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_genero_nombre_alter_libro_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='libros',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='prestamo',
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.libro'),
        ),
    ]
